name: api-test
on:
  push:
    branches:
      - github_actions
jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm run-script api-test
        env:
          MAPBOX_USER_NAME: ${{secrets.MAPBOX_USER_NAME}}
          MAPBOX_API_KEY: ${{secrets.MAPBOX_API_KEY}}
      - uses: actions/upload-artifact@v1
        with:
          name: API Test Report
          path: newman/*.html
